### ISSUE TITLE
無法執行訓練

### ISSUE THREAD

**Issue by jerry900106** [ADT109119/Bert-VITS2-Colab#2]
請問在第四步執行後最後跳出
Root Cause (first observed failure):
[0]:
  time      : 2024-05-03_09:38:42
  host      : 909a4c7aef29
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 16890)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
就停止運行是哪裡出了問題?

**Comment by ADT109119** [comment]
以查出原因
有人改了這行所以訓練腳本就爆了
![image](https://github.com/ADT109119/Bert-VITS2-Colab/assets/106337749/56f7f721-fa5f-4079-96f0-f8a480f5d412)

**Comment by jerry900106** [comment]
所以請問這個腳本是否還能使用嗎?

**Comment by ADT109119** [comment]
> 請問這個腳本是否還能使用嗎?

已修復

現在會在安裝函式庫時下載備份的舊訓練腳本

可以正常訓練

**Comment by jerry900106** [comment]
好的~非常謝謝您的修正
